name: 'Setup Node.js and pnpm'
description: 'Setup Node.js and pnpm with caching'
runs:
    using: 'composite'
    steps:
      - name: Config Git Info
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store cache directory
        shell: bash
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        shell: bash
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js
        shell: bash
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'